# Generated by Django 5.0.6 on 2026-05-19 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('proposals', '0001_initial'),
        ('requirements_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='requirement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='requirements_app.requirement'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='catalog_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalogitem'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proposals.proposal'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalitem',
            unique_together={('proposal', 'catalog_item')},
        ),
    ]
