# Generated by Django 5.0.6 on 2026-09-14 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BMRTrackerRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("client_name", models.TextField(blank=True, default="")),
                ("product", models.TextField(blank=True, default="")),
                (
                    "batch_no",
                    models.TextField(blank=True, default="", verbose_name="Batch No"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bmr_tracker_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BMRTrackerFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("drive_url", models.URLField()),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bmr_tracker_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bmr_tracker_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="bmr_tracker.bmrtrackerrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bmrtrackerrecord",
            index=models.Index(
                fields=["client_name"], name="bmr_tracker_client__ad4486_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bmrtrackerrecord",
            index=models.Index(
                fields=["batch_no"], name="bmr_tracker_batch_n_5c379c_idx"
            ),
        ),
    ]
