# Generated by Django 5.0.6 on 2026-05-19 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('requirements_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requirements_app.requirementproduct'),
        ),
        migrations.AddField(
            model_name='filerecord',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='requirements_app.requirement'),
        ),
    ]
