# Generated by Django 5.0.6 on 2026-05-30 08:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_status'),
        ('crm_master_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_no', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('no_of_products', models.PositiveIntegerField(blank=True, null=True)),
                ('moq', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='MOQ')),
                ('project_stage', models.CharField(choices=[('new_lead', 'New Lead'), ('order_closed', 'Order Closed'), ('lead_closed', 'Lead Closed'), ('not_responding', 'Not Responding'), ('proposal', 'Proposal'), ('costing', 'Costing'), ('sample', 'Sample'), ('order_booked', 'Order Booked'), ('packaging', 'Packaging'), ('design', 'Design'), ('printing', 'Printing'), ('production', 'Production'), ('batch_testing', 'Batch Testing'), ('filling', 'Filling'), ('transit', 'Transit'), ('derma_testing', 'Derma Testing')], db_index=True, default='new_lead', max_length=30)),
                ('sample_booked_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_phone', on_delete=django.db.models.deletion.PROTECT, related_name='crm_projects', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects_created', to=settings.AUTH_USER_MODEL)),
                ('formulation_poc', models.ForeignKey(blank=True, limit_choices_to={'role': 'poc_formulation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects_as_formulation', to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm_master_data.manufacturer')),
                ('sales_poc', models.ForeignKey(blank=True, limit_choices_to={'role': 'poc_sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects_as_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyLearning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_learnings_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_learnings', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(blank=True, default='', max_length=30)),
                ('sub_stage_key', models.CharField(blank=True, default='', max_length=60)),
                ('drive_file_id', models.CharField(max_length=255)),
                ('drive_url', models.URLField()),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='document', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='crm_projects.crmproject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_key', models.CharField(db_index=True, max_length=60)),
                ('milestone_display', models.CharField(max_length=120)),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('delayed', 'Delayed')], db_index=True, default='on_track', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(blank=True, default='', max_length=30)),
                ('sub_stage_key', models.CharField(blank=True, default='', max_length=60)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes_added', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StageCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(choices=[('new_lead', 'New Lead'), ('order_closed', 'Order Closed'), ('lead_closed', 'Lead Closed'), ('not_responding', 'Not Responding'), ('proposal', 'Proposal'), ('costing', 'Costing'), ('sample', 'Sample'), ('order_booked', 'Order Booked'), ('packaging', 'Packaging'), ('design', 'Design'), ('printing', 'Printing'), ('production', 'Production'), ('batch_testing', 'Batch Testing'), ('filling', 'Filling'), ('transit', 'Transit'), ('derma_testing', 'Derma Testing')], max_length=30)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_completions', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['project', 'stage_key'],
            },
        ),
        migrations.CreateModel(
            name='SubStageCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_key', models.CharField(max_length=30)),
                ('sub_stage_key', models.CharField(max_length=60)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_stages_completed', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_stage_completions', to='crm_projects.crmproject')),
            ],
        ),
        migrations.AddIndex(
            model_name='crmproject',
            index=models.Index(fields=['project_stage', '-created_at'], name='crm_project_project_4ae6ec_idx'),
        ),
        migrations.AddIndex(
            model_name='crmproject',
            index=models.Index(fields=['client', '-created_at'], name='crm_project_client__95a235_idx'),
        ),
        migrations.AddIndex(
            model_name='keylearning',
            index=models.Index(fields=['project'], name='crm_project_project_3205f8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfile',
            index=models.Index(fields=['project', 'stage_key'], name='crm_project_project_5656e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmilestone',
            unique_together={('project', 'milestone_key')},
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', 'stage_key'], name='crm_project_project_822159_idx'),
        ),
        migrations.AddIndex(
            model_name='projectnote',
            index=models.Index(fields=['project', '-created_at'], name='crm_project_project_0877fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stagecompletion',
            unique_together={('project', 'stage_key')},
        ),
        migrations.AddIndex(
            model_name='substagecompletion',
            index=models.Index(fields=['project', 'stage_key'], name='crm_project_project_fc6f0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='substagecompletion',
            unique_together={('project', 'stage_key', 'sub_stage_key')},
        ),
    ]
