# Generated by Django 5.x on 2026-05-30
from django.db import migrations

def backfill_stage_completions(apps, schema_editor):
    # ponytail: no-op — STAGE_DEFINITIONS was removed; fresh DBs have no projects to backfill
    pass

def rollback_stage_completions(apps, schema_editor):
    # In rollback, we do not need to do anything since the completion states 
    # will be re-evaluated when the user toggles/checks them.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_stage_completions, rollback_stage_completions),
    ]
