# Generated by Django 5.x on 2026-05-30
from django.db import migrations
from django.utils import timezone

def backfill_stage_completions(apps, schema_editor):
    CRMProject = apps.get_model('crm_projects', 'CRMProject')
    StageCompletion = apps.get_model('crm_projects', 'StageCompletion')
    SubStageCompletion = apps.get_model('crm_projects', 'SubStageCompletion')
    
    # We import STAGE_DEFINITIONS directly. Since this is a data migration, 
    # it's safe to use the definitions defined in stage_definitions.py.
    from apps.crm_projects.stage_definitions import STAGE_DEFINITIONS

    for project in CRMProject.objects.all():
        for stage_def in STAGE_DEFINITIONS:
            stage_key = stage_def['key']
            sub_stages = stage_def.get('sub_stages', [])
            if not sub_stages:
                continue

            mandatory_keys = [ss['key'] for ss in sub_stages if ss['mandatory']]
            
            # If no sub-stages are marked mandatory, we require all sub-stages to be completed
            keys_to_check = mandatory_keys if mandatory_keys else [ss['key'] for ss in sub_stages]

            completed_keys = set(
                SubStageCompletion.objects.filter(
                    project=project, stage_key=stage_key, completed=True
                ).values_list('sub_stage_key', flat=True)
            )
            all_done = all(k in completed_keys for k in keys_to_check)

            sc, _ = StageCompletion.objects.get_or_create(project=project, stage_key=stage_key)
            if all_done:
                if not sc.is_complete:
                    sc.is_complete = True
                    sc.completed_at = timezone.now()
                    sc.save(update_fields=['is_complete', 'completed_at'])
            else:
                if sc.is_complete:
                    sc.is_complete = False
                    sc.completed_at = None
                    sc.save(update_fields=['is_complete', 'completed_at'])

def rollback_stage_completions(apps, schema_editor):
    # In rollback, we do not need to do anything since the completion states 
    # will be re-evaluated when the user toggles/checks them.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_stage_completions, rollback_stage_completions),
    ]
