# Generated by Django 5.0.6 on 2026-06-03 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_master_data', '0002_initial'),
        ('crm_projects', '0002_backfill_stage_completions'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmproject',
            name='batch_testing_vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type': 'testing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_batch_testing', to='crm_master_data.vendor'),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='derma_testing_vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type': 'testing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_derma_testing', to='crm_master_data.vendor'),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='designer',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type': 'designer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_designer', to='crm_master_data.vendor'),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='packaging_vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type': 'packaging'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_packaging_vendor', to='crm_master_data.vendor'),
        ),
        migrations.AddField(
            model_name='crmproject',
            name='printer',
            field=models.ForeignKey(blank=True, limit_choices_to={'vendor_type': 'printing'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_printer', to='crm_master_data.vendor'),
        ),
    ]
