# Generated by Django 5.0.6 on 2026-06-03 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0003_add_vendor_assignment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('sample', 'Sample'), ('advance', 'Advance'), ('packaging', 'Packaging'), ('printing', 'Printing'), ('derma_testing', 'Derma Testing'), ('other_service', 'Other Service'), ('shipment_printing', 'Shipment - Printing'), ('shipment_packaging', 'Shipment - Packaging'), ('shipment_testing', 'Shipment - Testing')], db_index=True, max_length=30)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comments', models.TextField(blank=True, default='')),
                ('invoice_drive_id', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_drive_url', models.URLField(blank=True, default='')),
                ('invoice_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_payments_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['project', '-payment_date'], name='crm_project_project_f68181_idx')],
            },
        ),
    ]
