# Generated by Django 5.0.6 on 2026-06-08 06:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_client_product_fields'),
        ('crm_master_data', '0004_backfill_team_members'),
        ('crm_projects', '0008_stage_task_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('planned_closure_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('task_status', models.CharField(choices=[('not_started', 'Not Started'), ('wip', 'WIP'), ('pending', 'Pending'), ('closed', 'Closed')], db_index=True, default='not_started', max_length=15)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='crmproject',
            name='crm_project_project_4ae6ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='substagecompletion',
            name='crm_project_project_fc6f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='projectpayment',
            new_name='crm_project_vendor__755eaa_idx',
            old_name='crm_proj_vendor_date_idx',
        ),
        migrations.RenameIndex(
            model_name='projectpayment',
            new_name='crm_project_manufac_3a0edb_idx',
            old_name='crm_proj_mfr_date_idx',
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='actual_closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='last_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_tasks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='planned_closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagecompletion',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='stage_key',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='projectnote',
            name='stage_key',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddIndex(
            model_name='crmproject',
            index=models.Index(fields=['phase', '-created_at'], name='crm_project_phase_6a7ee2_idx'),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_standalone_tasks', to='crm_master_data.internalteammember'),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_phone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_tasks', to='clients.client'),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_tasks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_tasks_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standalonetask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_tasks', to='crm_projects.crmproject'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_comments_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='stage_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm_projects.stagecompletion'),
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='standalone_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm_projects.standalonetask'),
        ),
    ]
