# Generated by Django 5.0.6 on 2026-06-12 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0010_resample_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='settlement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settles_payable', to='crm_projects.projectpayment'),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='direction',
            field=models.CharField(choices=[('paid', 'Paid'), ('received', 'Received'), ('payable', 'Payable'), ('receivable', 'Receivable')], db_index=True, max_length=10),
        ),
    ]
