# Generated by Django 5.0.6 on 2026-06-29 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0013_order_booking_steps'),
        ('requirements_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmproject',
            name='source_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_projects', to='requirements_app.requirement'),
        ),
    ]
