# Generated by Django 5.0.6 on 2026-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0020_update_shipment_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmproject',
            name='sample_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
