# Generated by Django 5.0.6 on 2026-07-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientnote'),
        ('crm_projects', '0022_add_commercial_sample_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpayment',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_phone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_flow_payments', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='projectpayment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm_projects.crmproject'),
        ),
    ]
