# Generated by Django 5.0.6 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_migrate_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('poc_sales', 'POC-Sales'), ('poc_formulation', 'POC-Formulation'), ('poc_ops', 'POC-Ops')], default='poc_sales', max_length=20),
        ),
    ]
