# Generated by Django 5.0.6 on 2026-07-10 06:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=150)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_type', models.CharField(blank=True, default='', max_length=150)),
                ('no_of_ordered_by_client', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='No. Of Ordered by Client')),
                ('quantity_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('used_in_batch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('damaged_missing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Damaged / Missing')),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_name'], name='packaging_i_client__81eece_idx'), models.Index(fields=['vendor_name'], name='packaging_i_vendor__5e91af_idx')],
            },
        ),
    ]
