# Generated by Django 5.0.6 on 2026-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingrecord',
            name='no_of_ordered_by_client',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='No. Of Ordered by Client'),
        ),
    ]
