# Generated by Django 5.0.6 on 2026-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_inventory', '0002_alter_packagingrecord_no_of_ordered_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingrecord',
            name='quantity_sent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
