# Generated by Django 5.0.6 on 2026-07-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging_inventory', '0003_alter_packagingrecord_quantity_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingrecord',
            name='damaged_missing',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Damaged / Missing'),
        ),
        migrations.AlterField(
            model_name='packagingrecord',
            name='price_per_unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='packagingrecord',
            name='used_in_batch',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
