# Generated by Django 5.0.6 on 2026-09-14 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleTrackerRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("client_name", models.TextField(blank=True, default="")),
                ("product_type", models.TextField(blank=True, default="")),
                ("product_details", models.TextField(blank=True, default="")),
                (
                    "sample_attempt_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Sample Attempt Count"
                    ),
                ),
                (
                    "sample_no",
                    models.TextField(blank=True, default="", verbose_name="Sample No"),
                ),
                (
                    "sample_approved",
                    models.TextField(
                        blank=True, default="", verbose_name="Sample Approved"
                    ),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_tracker_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SampleTrackerFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("drive_url", models.URLField()),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sample_tracker_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample_tracker_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="sample_tracker.sampletrackerrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sampletrackerrecord",
            index=models.Index(
                fields=["client_name"], name="sample_trac_client__450105_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sampletrackerrecord",
            index=models.Index(
                fields=["sample_no"], name="sample_trac_sample__2dc417_idx"
            ),
        ),
    ]
