# Generated by Django 5.0.6 on 2026-07-09 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=150)),
                ('client_name', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('ingredient_use', models.CharField(blank=True, default='', max_length=255, verbose_name='Ingredient use / purpose')),
                ('quantity_sent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity Sent (gm)')),
                ('used_in_batch', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_name'], name='ingredient__client__6f8189_idx'), models.Index(fields=['vendor_name'], name='ingredient__vendor__6106f6_idx')],
            },
        ),
    ]
