# Generated by Django 5.0.6 on 2026-05-19 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.CharField(blank=True, default='', max_length=50)),
                ('poc', models.CharField(blank=True, default='', max_length=100)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('body_part', models.CharField(blank=True, default='', max_length=50)),
                ('product_type', models.CharField(blank=True, default='', max_length=50)),
                ('sub_product_type', models.CharField(blank=True, default='', max_length=50)),
                ('kb_tag1', models.CharField(blank=True, default='', max_length=100)),
                ('kb_tag2', models.CharField(blank=True, default='', max_length=100)),
                ('kb_tag3', models.CharField(blank=True, default='', max_length=100)),
                ('specific_ingredients', models.TextField(blank=True, default='')),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('fragrance', models.CharField(blank=True, default='', max_length=20)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('packaging_type', models.CharField(blank=True, default='', max_length=50)),
                ('per_kg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manufacturing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tentative_packaging_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('label_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tentative_monocarton_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('potential_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['body_part', 'product_type', 'sub_product_type'],
                'indexes': [models.Index(fields=['body_part'], name='catalog_cat_body_pa_f5a4b6_idx'), models.Index(fields=['product_type'], name='catalog_cat_product_32f524_idx'), models.Index(fields=['sub_product_type'], name='catalog_cat_sub_pro_45e089_idx')],
            },
        ),
    ]
