# Generated by Django 5.0.6 on 2026-05-19 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('body_part', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('sub_category', models.CharField(blank=True, default='', max_length=50)),
                ('key_benefits', models.JSONField(blank=True, default=list)),
                ('size', models.CharField(blank=True, default='', max_length=20)),
                ('packaging_type', models.CharField(blank=True, default='', max_length=20)),
                ('packaging_notes', models.TextField(blank=True, default='')),
                ('planned_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('specific_ingredient', models.TextField(blank=True, default='')),
                ('benchmark_product', models.CharField(blank=True, default='', max_length=255)),
                ('has_color', models.BooleanField(blank=True, null=True)),
                ('color_details', models.TextField(blank=True, default='')),
                ('has_fragrance', models.BooleanField(blank=True, null=True)),
                ('fragrance_details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('target_audience_age', models.CharField(blank=True, default='', max_length=50)),
                ('no_of_products', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('proposal_ready', 'Proposal Ready')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(db_column='client_phone', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='clients.client')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
