# Generated by Django 5.0.6 on 2026-05-19 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requirementproduct',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='requirements_app.requirement'),
        ),
        migrations.AlterUniqueTogether(
            name='requirementproduct',
            unique_together={('requirement', 'row_number')},
        ),
    ]
