# Generated by Django 5.0.6 on 2026-09-03 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingClientRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_name", models.TextField(blank=True, default="")),
                ("packaging_name", models.TextField(blank=True, default="")),
                ("size", models.TextField(blank=True, default="")),
                (
                    "glass_pet",
                    models.TextField(blank=True, default="", verbose_name="Glass/Pet"),
                ),
                ("moq", models.TextField(blank=True, default="", verbose_name="MOQ")),
                (
                    "cost_to_ss",
                    models.TextField(blank=True, default="", verbose_name="Cost To SS"),
                ),
                ("cost_to_client", models.TextField(blank=True, default="")),
                ("vendor_name", models.TextField(blank=True, default="")),
                ("poc", models.TextField(blank=True, default="", verbose_name="POC")),
                ("contact_details", models.TextField(blank=True, default="")),
                ("poc2", models.TextField(blank=True, default="", verbose_name="POC2")),
                ("cd2", models.TextField(blank=True, default="", verbose_name="CD2")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packaging_client_records_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client_name"], name="packaging_c_client__92b663_idx"
                    ),
                    models.Index(
                        fields=["vendor_name"], name="packaging_c_vendor__02df1c_idx"
                    ),
                ],
            },
        ),
    ]
