# Generated by Django 5.0.6 on 2026-09-14 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packaging_clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="packagingclientrecord",
            old_name="moq",
            new_name="client_moq",
        ),
        migrations.AlterField(
            model_name="packagingclientrecord",
            name="client_moq",
            field=models.TextField(blank=True, default="", verbose_name="Client MOQ"),
        ),
        migrations.AddField(
            model_name="packagingclientrecord",
            name="vendor_moq",
            field=models.TextField(blank=True, default="", verbose_name="Vendor MOQ"),
        ),
        migrations.CreateModel(
            name="PackagingClientFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("drive_url", models.URLField()),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "packaging_client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="packaging_clients.packagingclientrecord",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packaging_client_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
