# Generated by Django 5.0.6 on 2026-07-07 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_type', models.CharField(blank=True, default='', max_length=150)),
                ('product_name', models.CharField(max_length=200)),
                ('packaging_type', models.CharField(blank=True, default='', max_length=150)),
                ('pack_size', models.CharField(blank=True, default='', max_length=50)),
                ('moq', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Quantity / MOQ (units)')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_records_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_name'], name='batch_regis_client__ecc4d3_idx'), models.Index(fields=['batch_number'], name='batch_regis_batch_n_8cb0db_idx')],
            },
        ),
    ]
