# Generated by Django 5.0.6 on 2026-09-14 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch_register", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="batchrecord",
            name="ctri_no",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="CTRI No"
            ),
        ),
        migrations.AddField(
            model_name="batchrecord",
            name="document_no",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Document No"
            ),
        ),
        migrations.CreateModel(
            name="BatchRecordFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255)),
                ("drive_url", models.URLField()),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="batch_register.batchrecord",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_record_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
