# Generated by Django 5.0.6 on 2026-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_status_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='how_many_units_per_product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='no_of_products',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='planned_selling_price_range',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
