# Generated by Django 5.0.6 on 2026-07-01 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='clients.client'),
        ),
    ]
