# Generated by Django 5.0.6 on 2026-07-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lead_sub_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('initial_conversation', 'Initial Conversation'), ('proposal', 'Proposal shared'), ('costing', 'Costing shared'), ('sample', 'Sample'), ('order', 'Order'), ('production', 'Production'), ('testing', 'Testing'), ('filling', 'Filling'), ('order_dispatch', 'Order Dispatch'), ('order_closed', 'Order Closed'), ('lead_closed', 'Lost')], default='initial_conversation', max_length=40),
        ),
    ]
