# Generated by Django 5.0.6 on 2026-07-03 08:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_projects', '0014_add_source_requirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_type', models.CharField(choices=[('service', 'Service Invoice'), ('product_batch', 'Product with Batch'), ('product_simple', 'Product Simple'), ('service_size', 'Service with Size')], max_length=20)),
                ('invoice_number', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('client_gstin', models.CharField(blank=True, default='0', max_length=30)),
                ('billing_address', models.TextField(blank=True, default='0')),
                ('shipping_address', models.TextField(blank=True, default='0')),
                ('eway_bill_no', models.CharField(blank=True, default='XX', max_length=50)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('items', models.JSONField(default=list)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('drive_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm_projects.crmproject')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='invoices_in_project_3171df_idx')],
            },
        ),
    ]
