# Generated by Django 5.0.6 on 2026-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service', 'Service Invoice'), ('product_batch', 'Advance Invoice'), ('product_simple', 'Sample Invoice'), ('service_size', 'Container Invoice'), ('printing', 'Printing Invoice')], max_length=20),
        ),
    ]
