# Generated by Django 5.0.6 on 2026-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_printing_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service', 'Service Invoice'), ('product_batch', 'Advance Invoice'), ('product_simple', 'Sample Invoice'), ('service_size', 'Container Invoice'), ('printing', 'Printing Invoice'), ('final', 'Final Invoice')], max_length=20),
        ),
    ]
