# Generated by Django 5.0.6 on 2026-07-21 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_projects', '0024_projectpayment_client_fk_to_m2m'),
        ('invoices', '0003_final_invoice_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('client_gstin', models.CharField(blank=True, default='', max_length=30)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('phone_no', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('services', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_infos_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_info', to='crm_projects.crmproject')),
            ],
        ),
    ]
