# Generated by Django 5.0.6 on 2026-07-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_billinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('service', 'Service Invoice'), ('product_batch', 'Advance Invoice'), ('product_simple', 'Sample Invoice'), ('printing', 'Packaging or Printing Invoice'), ('final', 'Final Invoice')], max_length=20),
        ),
    ]
