# Generated by Django 5.0.6 on 2026-07-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='processing_charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
