# Generated by Django 5.0.6 on 2026-07-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_processing_charge_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dispatch_address',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='dispatch_from_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='dispatch_from_gstin',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='dispatch_from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_from_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_from_gstin',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dispatch_from_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('product_batch', 'Advance Invoice'), ('product_simple', 'Sample Invoice'), ('printing', 'Packaging or Printing Invoice'), ('final', 'Final Invoice')], max_length=20),
        ),
    ]
