# Generated by Django 5.0.6 on 2026-07-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoice_dispatch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
