# Generated by Django 5.0.6 on 2026-05-30 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_master_data', '0001_initial'),
        ('crm_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_ratings', to='crm_projects.crmproject'),
        ),
        migrations.AddField(
            model_name='manufacturerrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprojectpayment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_payments', to='crm_master_data.manufacturer'),
        ),
        migrations.AddField(
            model_name='vendorprojectpayment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='crm_projects.crmproject'),
        ),
        migrations.AddField(
            model_name='vendorprojectpayment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_payments', to='crm_master_data.vendor'),
        ),
        migrations.AddField(
            model_name='vendorrating',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ratings', to='crm_projects.crmproject'),
        ),
        migrations.AddField(
            model_name='vendorrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorrating',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='crm_master_data.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='manufacturerrating',
            unique_together={('manufacturer', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorrating',
            unique_together={('vendor', 'project')},
        ),
    ]
