# Generated by Django 5.0.6 on 2026-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_master_data', '0004_backfill_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalteammember',
            name='team',
            field=models.CharField(choices=[('formulation', 'Formulation Team'), ('sales', 'Sales Team'), ('ops', 'Ops Team')], db_index=True, max_length=20),
        ),
    ]
