# Generated by Django 5.0.6 on 2026-07-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_master_data', '0005_add_ops_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalteammember',
            name='team',
            field=models.CharField(choices=[('formulation', 'Formulation Team'), ('sales', 'Sales Team'), ('ops', 'Ops Team'), ('admin', 'Admin')], db_index=True, max_length=20),
        ),
    ]
