# Generated by Django 5.0.6 on 2026-07-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_master_data', '0008_seed_vendor_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBaseRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdsco_registration', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('content_creation', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('logo_design', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('label_mono_carton_design', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('dermatology_testing', models.DecimalField(decimal_places=2, default=15000, max_digits=10)),
                ('spf_testing', models.DecimalField(decimal_places=2, default=20000, max_digits=10)),
                ('formulation_support', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('digital_brand_building_support', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
