# Generated by Django 5.0.6 on 2026-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_master_data', '0009_servicebaserates'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebaserates',
            name='batch_testing',
            field=models.DecimalField(decimal_places=2, default=4500, max_digits=10),
        ),
    ]
